/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_eiffel_example_MainActivity */

#ifndef _Included_com_example_eiffel_example_MainActivity
#define _Included_com_example_eiffel_example_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_eiffel_example_MainActivity
 * Method:    initialize_eiffel_runtime
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_eiffel_1example_MainActivity_initialize_1eiffel_1runtime
  (JNIEnv *, jobject);

/*
 * Class:     com_example_eiffel_example_MainActivity
 * Method:    close_eiffel_runtime
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_eiffel_1example_MainActivity_close_1eiffel_1runtime
  (JNIEnv *, jobject);

/*
 * Class:     com_example_eiffel_example_MainActivity
 * Method:    get_hello_from_eiffel
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_eiffel_1example_MainActivity_get_1hello_1from_1eiffel
  (JNIEnv *, jobject);

/*
 * Class:     com_example_eiffel_example_MainActivity
 * Method:    get_fibonacci_sequence_from_eiffel
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_example_eiffel_1example_MainActivity_get_1fibonacci_1sequence_1from_1eiffel
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
